addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: 41839720-26b6-4226-a728-1b3941e62ac2
after_success:
- ./df-build.sh
before_install:
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  $HOME/.m2/settings.xml
branches: ''
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-stg.public-swarm.devfactory.com/travisWebHookListener?build_id=41839720-26b6-4226-a728-1b3941e62ac2
script: mvn clean install
sudo: false
# Modified by Insights Service at 2016-10-16 23:00:03.851922
